### ISSUE TITLE
appcast: the length attribute is never verified

### ISSUE THREAD

**Issue by stephenwade** [Deadpikle/NetSparkle#14]
The `length` attributes of the appcast `<item>`s (stored in `AppCastItem.UpdateSize`) are never checked. The size of the update file should be checked against this attribute before installation.

**Comment by Deadpikle** [comment]
Unnecessary. The DSA check is good enough to verify that we downloaded the right file.

**Comment by stephenwade** [comment]
What if people want to use this library without DSA checking? I'm sure the attribute is in the XML for a reason.

**Comment by Deadpikle** [comment]
The length attribute is not required to be in the XML file, so we should not rely on it. That and I'd hate to have a length attribute that was off by a byte or two do to a typo or differing operating system calculations.

The DSA check is the method we offer for file verification. If users decide not to use that method, then the users will need to perform their own verification by looking at `AppCastItems` themselves, performing their own hashing, etc.
