### ISSUE TITLE
appcast: the type attribute is never used

### ISSUE THREAD

**Issue by stephenwade** [Deadpikle/NetSparkle#15]
The `type` attributes of the appcast `<item>`s are never stored or checked. Should we verify that the media type (MIME type) offered by the server matches the `type` attribute before downloading the update?

**Comment by Deadpikle** [comment]
I'm going with not checking things on the server since macOS Sparkle does not verify the `type` attribute and we are trying to be compatible with that library. Nonetheless, I added `AppCastItem.MIMEType` so that users can check the mime type themselves if desired.
