### ISSUE TITLE
feature request: make RunDownloadedInstaller method virtual & protected

### ISSUE THREAD

**Issue by delfuria** [Deadpikle/NetSparkle#29]
I'm trying to integrate NetSparkle in my app, but i need to overwrite this method for customize the final step of installation.
I would like to execute custom code so i'll be able to manage other files type than .exe, .msi and so on.
The method GetInstallerCommand is yet protected and virtual but is not enough to reach my goal.

**Comment by Deadpikle** [comment]
@delfuria Is it fine if the function is still `async`? Do you not want to run an .exe/.msi at all? Do you want to hook into something before/after that executable runs (or before/after the program exits)? `RunDownloadedInstaller` also kills the currently running application -- is it fine if you handle that yourself, or do you want NetSparkle to still handle it? (Note to myself: will need to update documentation to let users know what to do when they override this function.)

I can see how this might be useful if you were using `NetSparkle` to update data files from a .zip or something, which wouldn't necessarily require a program restart.

**Comment by delfuria** [comment]
You are right, i would like to use a .zip file as delivery method for my upgrade.
I still need to restart the app after the inplace upgrade and i could reach to do this overriding GetInstallerCommand  and RunDownloadedInstaller.
Am i right ??
Thanks

**Comment by Deadpikle** [comment]
@delfuria You should try out 0.11.2. `RunDownloadedInstaller` is now protected and virtual. I refactored the application close logic to `QuitApplication()`. I didn't add new methods to actually relaunch the software for you, yet, but you should be able to tweak and reuse the logic in `RunDownloadedInstaller` to relaunch the software with a .bat file yourself.

**Comment by Deadpikle** [comment]
@delfuria NuGet package updated at https://www.nuget.org/packages/NetSparkle.New/ ; I'll assume you're good to go unless I hear otherwise!
