### ISSUE TITLE
WindowsForms in UI interfaces

### ISSUE THREAD

**Issue by enscope** [Deadpikle/NetSparkle#39]
Is there an actual reason to why there is a `DialogResult` used in UI interfaces? As I am looking at it, there are only two interfaces, where `DialogResult` is used:

- `IUpdateAvailable.Result` - where `DialogResult` signalises, whether the update should be handled; where, it might be better to have a separate enum with required values and let the implementation of the interface do the translation; this way, it will be separated from a UI framework;
- `IDownloadProgress.ShowDialog()` - where `DialogResult` signalises a boolean (`Abort` || `Result` -> cancel, otherwise continue).

My solution proposal would be to have `IUpdateAvailable.Result` return custom enum with values `InstallUpdate`, `SkipUpdate`, `InstallLater` and `IDownloadProgress.ShowDialog()` return just `boolean`, indicating success. 

Tweaks to the existing default forms are trivial, but it is a breaking change for existing custom-UI code, yet the changes are trivial as well (it may even be viable to include some simple converters to help with converting code to default behaviour).

As for the implementation, I am going to implement these changes to the code anyway for my project, but I would kind of like to see it in public release as well, as in my opinion, the changes make sense.

**Comment by Deadpikle** [comment]
👋 Hi @enscope! That's an interesting (and good, I think) proposal! I'm a bit busy right now with work and (USA) Thanksgiving, but I will try to take a look at this sometime in the next week or two. I'll test it out with the project I'm using NetSparkle in, and if it looks good, we'll move forward. Now is the time for breaking changes as well, since I (eventually) am going to be updating things to a "2.0" version and things are definitely unstable right now.

Related: #26

**Comment by enscope** [comment]
Cool. I think I will take a look at the last dialog without interface - CheckingForUpdatesWindow - as well, because I need to customise it for my project too. Is it ok with you?

**Comment by Deadpikle** [comment]
See latest commits (and botched pull request) for resolving this issue. Will close this issue once we resolve whether or not you want to redo that PR due to my mistake.

Feel free to submit another PR for that window if you like! I, er, won't mess up things again this time 😓

**Comment by Deadpikle** [comment]
Resolved in recent commits (4f378e66b5215ba729b130e1da48f34428c9486a, 58cfe8254970204dbe72cbf4aaf68d86c82dc465) and PR #40
