### ISSUE TITLE
UpdateAvailableWindow sometimes shows two different version strings (with/without revision)

### ISSUE THREAD

**Issue by ndreisg** [Deadpikle/NetSparkle#55]
`UpdateAvailableWindow.getVersion` function returns wrong number of fields.

    private string getVersion(Version version)
    {
        if (version.Build != 0) // should be Revision
            return version.ToString();
        if (version.Revision != 0) // should be Build
            return version.ToString(3);
        return version.ToString(2);
    }

According to AssemblyInfo.cs the format of a version string is: `Major.Minor.Build.Revision`
So currently the function returns all components for a version string like 1.0.1.0 but only three components for a version string like 1.0.0.1

**Comment by Deadpikle** [comment]
Thanks for the report. I also added some unit tests to verify the fix. (This project needs unit tests so badly...yet another thing to add to the 2.0 list)
