### ISSUE TITLE
Multiple Hosts for AppCast file

### ISSUE THREAD

**Issue by christianerlinger** [Deadpikle/NetSparkle#56]
Hi Folks,

in my project I have some sort of load balancing between multiple server hosts. In my case it should be possible to load updates from each of the configured hosts; 

e.g. 
server1, server2, server3

server1 gets a new appcast xml so the new version should be pulled from that current server by a number of clients (or all of them - depends on the interval check)

when server1 gets a new version shortly after that server2 and server3 gets the new version of the software as well. 

is something like that possible?

TIA & best regards
Christian

**Comment by Deadpikle** [comment]
Hi Christian,

Hmmm, that's an interesting question. Am I understanding you correctly that you want to download the **software updates** from different servers, not the appcast? If this is the case, we support the ability for your AppCast to change dynamically based on users, since there's no reason you can't have NetSparkle call a script that generates the app cast dynamically on the server and thus feeds X client D appcast and Y client E appcast. In other words, it's all on the server's logic to handle which clients get which app casts or app cast URLs. So, I'd recommend having a centralized script (or some script that works across all your servers) that can return the appcast dynamically with modified URLs to the software update depending on which server you want to hit.

However, I don't believe we support multiple app cast URLs within a single running instance of NetSparkle, especially since I'm not sure how we'd coordinate with X server to see which URL we should use.

Am I understanding your use case properly?

Thanks for using NetSparkle!

**Comment by christianerlinger** [comment]
Hi!

Thanks for your quick response.

I would need multiple AppCast URLs yes. 

We have a...well let's call it a J2EE application (there are a multitude of components running on different technologies) running on multiple servers; the installation layout is (except for the hostname) the very same. The clients can start the application against one of the X configured servers. If one of the servers fail the application will restart against another server.

There are some client components (some sort of a browser, and some other programs like the one which does the failover etc.) I need to autoupdate. The installer for these client components are located on the server. 

Now when we install a new version of our software the client tools will be installed on the application servers as well. 

The clients know all the available application servers - so the check could be the following:

say I have 3 Servers; as1, as2 and as3 running all V1 of our software

Once I bring them to a new version (V1.1) for the sake of example I'll start with as3; so after the installer is finished as1 and as3 run V1 of the software as2 run V1.1.

So the client will
- check as1 - V1 is installed on the server, V1 is installed on the client - OK, nothing to do
- check as2 - V1 is installed on the server, V1 is installed on the client - OK, nothing to do
- check as3 - V1.1 is installed on the server, V1 is installed on the client - need to autoupdate

after restart as1 and as2 will have different (lower) versions - which doesn't interest me much (while the upgrade runs the client software runs in a limited maintenance mode).

The timeframe between checks should be distributed between all the clients, so not all clients update at once - so the next client could pulls it's update from as1 after its updated to V1.1.

While the database upgrade still modifies all the necessary tables etc. all the clients should upgrade themselves to the new version and should be able to start the new version after the database upgrade is finished (lasts approx 30mins at max) we would start the client application.

So in short - yes - I would need different URLs which somehow all point to a appcast XML with almost the same layout like (from your example):

The first Application Server would have a layout like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- as1 -->
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
[...]
        <item>
            <title>Version 2.0 (2 bugs fixed; 3 new features)</title
            <pubDate>Thu, 27 Oct 2016 10:30:00 +0000</pubDate>
            <enclosure url="https://as1/installer.exe"
                       sparkle:version="1.0" />
        </item>
[...]
```
And the second one like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- as2 -->
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
[...]
        <item>
            <title>Version 2.0 (2 bugs fixed; 3 new features)</title
            <pubDate>Thu, 27 Oct 2016 10:30:00 +0000</pubDate>
            <enclosure url="https://as2/installer.exe"
                       sparkle:version="1.0" />
        </item>
[...]
```

After an upgrade sparkle:version would be 1.1 or something.

I hope I have shed some more light on my requirement :)

thanks & regards
Christian

**Comment by Deadpikle** [comment]
Hmmmm, very interesting! Thanks for the huge amount of detail, there.

For now, I'm just mentally taking this one step at a time. First step would be to allow for multiple appcast URLs that were pinged at every X interval, or perhaps an additional setting to try one right after the other if one doesn't have updates (or similar). In looking at the code at a quick glance, the `_appcastUrl` doesn't seem too awful to refactor to something like a `_appcastIndex` that points to an index in an appcast `string` array or similar.

I probably won't have time until this weekend to take a serious crack at it, but do let me know if you think of more things. 😄

**Comment by christianerlinger** [comment]
Hi,

Thanks for considering this :)!

Yes, I was thinking about keeping a list of urls. If there is no update (or
a 404) for an entry just check the next one in the list.

As for now we are able to add and remove servers to our serverlist on the
fly - so I'd need to modify that list at runtime if I may be so bold and
add another request ;).

Thank you very much!
regards
Christian

**Comment by Deadpikle** [comment]
Wait, pause -- I thought about this more. We don't need to edit NetSparkle itself for multiple URLs. You can just create multiple instances of a `NetSparkle` object 😅 

Example (please ignore the fact that I did this all in the code behind for the Sample WPF app -- I trust that you know where best to implement this):

```
using System.Collections.Generic;
using System.Windows;

namespace NetSparkle.TestAppWPF
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private List<Sparkle> _sparkleList;

        public MainWindow()
        {           
            InitializeComponent();

            // set icon in project properties!

            int numberOfServers = 3;
            _sparkleList = new List<Sparkle>();
            for (int i = 0; i < numberOfServers; i++)
            {
                // can edit the URL as needed for each of your different servers
                AddSparkle("https://deadpikle.github.io/NetSparkle/files/sample-app/appcast.xml");
            }
        }

        private void AddSparkle(string url)
        {
            string manifestModuleName = System.Reflection.Assembly.GetEntryAssembly().ManifestModule.FullyQualifiedName;
            var icon = System.Drawing.Icon.ExtractAssociatedIcon(manifestModuleName);
            var sparkle = new Sparkle(url, icon);
            sparkle.SecurityProtocolType = System.Net.SecurityProtocolType.Tls12;
            _sparkleList.Add(sparkle);
        }
    
        private async void CheckAllServers()
        {
            var didFindUpdate = false;
            for (int i = 0; i < _sparkleList.Count; i++)
            {
                var updateInfo = await _sparkleList[i].CheckForUpdatesQuietly();
                if (updateInfo.Status == Enums.UpdateStatus.UpdateAvailable)
                {
                    // yay, download the update!!!11shift
                    didFindUpdate = true;
                    // show user the UI
                    //_sparkleList[i].ShowUpdateNeededUI(updateInfo.Updates);
                    // if you don't want to show the user the UI..
                    _sparkleList[i].SilentMode = Sparkle.SilentModeTypes.DownloadAndInstall; // or whatever...you can download silently
                    _sparkleList[i].StartLoop(true, true); // starts the update loop, which will eventually get the download started~
                    // ...unfortunately right now there isn't really a way to tell Sparkle to just go download and install an update
                    // outside of the loop. Sorry about that. `private void Update(AppCastItem[] updates)` really needs to be public or something.
                    break;
                }
                else
                {
                    // aw man, go on and try the next server if you want...
                }
            }
            if (!didFindUpdate)
            {
                // did we not find an update? Set a timer to restart this loop in X minutes/hours/days
            }
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            CheckAllServers();
        }
    }
}
```

This will even allow you to add new servers or remove servers to check just by modifying the `_sparkleList` .

This way, it's all controlled in your client -- silent/not silent updates, when to actually do the download and install, etc.  If you need to overwrite the quitting and install process, you can override `NetSparkle.RunDownloadedInstaller` -- this way you could run any maintenance mode scripts that you need to run before/after install.

I...think that solves the questions you had? Is that correct? Did I miss something?

**Comment by christianerlinger** [comment]
Hi!

Well, that sounds very promising, and if it works it should solve my
problem. should have thought of that myself :).

Currently I am on leave, so I can't try your solution - I'll get back to
you once I am back in action ;).

Thank you for the quick help!

Best regards
Christian

Am Di., 5. Feb. 2019, 13:18 hat Deadpikle <notifications@github.com>
geschrieben:

**Comment by christianerlinger** [comment]
Hi,

I am back in action and am trying your solution.

I'v stumbled upon something that might cause me problems though: 

I need to provide a DSA Signature of the programs. Now in the timeframe when server1 was upgraded and server2 will be upgraded there are 2 different DSA signautes (the old one and the new one). How would I prevent the clients to be in an upgrade loop in that Timeframe?

regards

**Comment by Deadpikle** [comment]
Hey,

You could enforce a minimum wait time before updates/checking servers for updates so that your client doesn't do this in rapid succession if you don't want your clients to be updating rapidly:

1. Checks for server 1 update, nothing
2. (Server 1 updates to 1.2 from 1.0)
3. Checks for server 2 update, grabs update to 1.1 and updates to 1.1
4. Checks for server 1 update, grabs update to 1.2 and updates to 1.2

Even still, the client will eventually get upgraded to the latest version, so there's no concern about there being a loop. **Make sure to bump your version appropriately in your appcast. NetSparkle will always grab the latest version.** Basically, NetSparkle checks `if (ClientVersion < ServerVersion) needsToRunUpdate();` -- it doesn't look at the DSA for anything at that point.

I'm not sure I'm understanding how there would be an upgrade loop -- NetSparkle checks for the latest version -- the DSA is only used for hashing to make sure the update and updates file is secure. Could you help me understand the upgrade loop you are concerned about?

**Comment by christianerlinger** [comment]
> **Make sure to bump your version appropriately in your appcast. NetSparkle will always grab the latest version.** Basically, NetSparkle checks `if (ClientVersion < ServerVersion) needsToRunUpdate();` -- it doesn't look at the DSA for anything at that point.

Alright, that was my missing information. My impression was that (as it seems to be obligatory) the DSA signature is used to determine if an upgrade is needed. If that would be the case the clients would toggle between those 2 versions.; so I didn't add it for my test. I certainly have an ascending version number however; so there should be no problem.

Not sure why in my current test I don't get an upgrade even though; I'll look further ;)

thanks & regards

**Comment by christianerlinger** [comment]
Hi,

I've run tests and the result is as I want it to be: the upgrade is pulled from the server with the higher version - no upgrade loops, and I am able to distribute the load between servers.

Thanks for your inputs - much appreciated :-)

best regards
Christian

**Comment by Deadpikle** [comment]
Woo hoo! Glad you got it working. I'll close this issue since the problem seems to be resolved.
