### ISSUE TITLE
NetSparkle doesn't correctly handle Sparkle items that use a redirect

### ISSUE THREAD

**Issue by Mostlypyjamas** [Deadpikle/NetSparkle#64]
The `InitDownloadAndInstallProcess` function assumes that the path that is given in the xml is a valid final filename and sets `_downloadTempFileName` to be that filename and creates a temporary directory to contain it.

There is a problem with sparkle app feeds that use a redirect mechanism like Microsoft AppCenter - for example the feed [https://api.appcenter.ms/v0.1/public/sparkle/apps/c27e6512-ceae-4665-82c5-c0d7f6a27f30](https://api.appcenter.ms/v0.1/public/sparkle/apps/c27e6512-ceae-4665-82c5-c0d7f6a27f30) suggests a download enclosure location of [https://rink.hockeyapp.net/api/2/apps/c27e6512ceae466582c5c0d7f6a27f30/app_versions/5789?format=zip&avtoken=26b4ee8fcdfde2e89ce5d7b54ad61f43172a32de&download_origin=hockeyapp&mctoken=ed71c9ffae166f2bfbfaf1335fcbaedb17cb0b0e](https://rink.hockeyapp.net/api/2/apps/c27e6512ceae466582c5c0d7f6a27f30/app_versions/5789?format=zip&avtoken=26b4ee8fcdfde2e89ce5d7b54ad61f43172a32de&download_origin=hockeyapp&mctoken=ed71c9ffae166f2bfbfaf1335fcbaedb17cb0b0e)  however this location is actually then redirected to download the final MSI file.

The issue is that the file is successfully downloaded by `WebClient.DownloadFileAsync`, but `_downloadTempFileName` has not been set to match the redirected filename, so `GetInstallerCommand` does not know how to call the downloaded file.

I've tried checking the response headers that WebClient returns but there doesn't seem to be any that show the "actual" filename that should be used, so I suspect it might need a rewrite to use an HTTP WebRequest instead as this can apparently retrieve the correct filename. I'm afraid that is beyond my abilities though!

**Comment by Deadpikle** [comment]
Closed by #63
