### ISSUE TITLE
Double message window

### ISSUE THREAD

**Issue by psionika** [Deadpikle/NetSparkle#72]
Hello! "Minibug" - two identical message box after manual check update, if your current version is up to date. 
Maybe the problem is here
https://github.com/Deadpikle/NetSparkle/blob/2ed743df782a0d4d9782cf851f381024b3c0a208/NetSparkle/NetSparkle.cs#L1497

**Comment by Deadpikle** [comment]
Hi @psionika ! Thanks for the report. This bug has been fixed! You were right on the money with where the problem was. I appreciate you pointing this out.
