### ISSUE TITLE
Text wrapping on Software Download (and no available update) dialog in 0.18

### ISSUE THREAD

**Issue by Mostlypyjamas** [Deadpikle/NetSparkle#78]
Hi,

We're using the 0,18 Nuget package, and we have an issue with the text in the dialogs wrapping on longer captions and it overlaying the Icon.

I know you're doing a lot of refactoring for v2, but would it be possible to get an updated fix and buget for 0.19 (yes, a cheeky request i know!) :)  

Thanks,

![image](https://user-images.githubusercontent.com/3703626/72338120-b6b01a00-36bb-11ea-9a34-03518f4b15e4.png)

**Comment by Mostlypyjamas** [comment]
Submitted a PR :)  https://github.com/Deadpikle/NetSparkle/pull/79

**Comment by Deadpikle** [comment]
@Mostlypyjamas  Not a problem to push to Nuget! Thank you for your contribution and the bug report. Nuget is processing a new build now -- labeled 0.18.1 since it was just a bug fix.
